requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta" 

[project]
name = "hsm-py"
version = "1.8.0"
description = "A hierarchical state machine implemented in Python"
authors = [
  {name = "Julian Krumow", email = "julian.krumow@artcom.de"},
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.pytest.ini_options]
minversion = "8.3"
addopts = "-ra"
testpaths = [
    "tests"
]
